class UniversalStrings {
  static const String signIn = "Sign In";
  static const String email = "E-mail";
  static const String mobileNumber = "Mobile Number";
  static const String password = "Password";
  static const String enterValidEmail = "Please Enter a Valid Email";
  static const String enterValidPassword = "Please enter atlease 6 characters";
  static const String forgetPassword = "Forget Password?";
  static const String remember = "Remember";
  static const String or = "Or";
  static const String dontHaveAccount = "Don't Have an Account?";
  static const String createAccount = "Create Account";
  static const String loginWithMobile = "Login with Mobile Number?";
  static const String loginWithEmail = "Login with Email?";
  static const String error = "OOPS! Something went wrong";
  static const String success = "Success";
  static const String home = "Home";
  static const String welcome = "Welcome";
  static const String bookAppointment = "Book An Appointment";
  static const String bookAppointmentId = "Book_Appointment";
  static const String myAppointments = "My Appointments";
  static const String myAppointmentsId = "My_Appointments";
  static const String wishlist = "WishList";
  static const String wishlistId = "WishList";
  static const String currentTreatment = "Current Treatments";
  static const String currentTreatmentId = "Current_Treatments";
  static const String todos = "To Do's";
  static const String todosId = "To_Do's";
}
